#I file di oxwall vengono recuperati dal download ufficiale
FROM php:5.6-apache

RUN apt-get update && apt-get upgrade -y && apt-get install -y wget nano cron unzip libzip-dev libpng-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev
RUN docker-php-ext-install mysql pdo pdo_mysql zip
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && docker-php-ext-install -j$(nproc) gd 
RUN wget -q -O /tmp/oxwall.zip https://developers.oxwall.com/dl/oxwall-1.8.4.1.zip
RUN unzip -qq /tmp/oxwall.zip -d /var/www/html && rm /tmp/oxwall.zip
RUN chown -R www-data:www-data /var/www/html/
RUN a2enmod rewrite

#TODO: cron job oxwall (localhost/ow_cron/run.php)
