#esempio singolo nodo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxwall-db-deployment
  labels:
    app: oxwall-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxwall-db
  template:
    metadata:
      labels:
        app: oxwall-db
    spec:
      containers:
      - name: oxwall-db
        image: mysql:5.7
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: oxwall-config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: oxwall-db-service
spec:
  type: NodePort
  selector:
    app: oxwall-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306