#esempio singolo nodo con storage locale
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxwall-web-deployment
  labels:
    app: oxwall-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxwall-web
  template:
    metadata:
      labels:
        app: oxwall-web
    spec:
      containers:
      - name: oxwall-web
        image: davideacanfora/oxwall:220601
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: oxwall-web-service
spec:
  type: NodePort
  selector:
    app: oxwall-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080