apiVersion: batch/v1
kind: CronJob
metadata:
  name: oxwall-web-cronjob
spec:
  schedule: "* * * * *" #ogni minuto
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oxwall-cronjob
            image: busybox:latest
            command:
            - sh
            - -c
            - wget -q -O /dev/null oxwall-web-service/ow_cron/run.php
          restartPolicy: OnFailure
