apiVersion: v1
kind: ConfigMap
metadata:
  name: ckan-config
data:
  CKAN_SITE_ID: default
  # On AWS, your CKAN_SITE_URL is the output of:
  # curl -s http://169.254.169.254/latest/meta-data/public-hostname
  # CKAN_SITE_URL=http://ec2-xxx-xxx-xxx-xxx.ap-southeast-2.compute.amazonaws.com
  # On OSX with Docker for Mac, your CKAN_SITE_URL is
  # CKAN_SITE_URL=http://docker.for.mac.localhost:5000
  # When running locally, CKAN_SITE_URL must contain the port
  CKAN_SITE_URL: http://localhost:5000
  CKAN_PORT: "5000"
  CKAN_SMTP_SERVER: smtp.corporateict.domain:25
  CKAN_SMTP_STARTTLS: "True"
  CKAN_SMTP_USER: user
  CKAN_SMTP_PASSWORD: pass
  CKAN_SMTP_MAIL_FROM: ckan@localhost

  POSTGRES_PASSWORD: ckan
  POSTGRES_PORT: "5432"

  # The datastore database will be created in the db container as docs
  # Readwrite user/pass will be ckan:POSTGRES_PASSWORD
  # Readonly user/pass will be datastore_ro:DATASTORE_READONLY_PASSWORD
  DATASTORE_READONLY_PASSWORD: datastore